matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o Antonette Antonette.c 
        - ./Antonette
        - gcc -o lavenya lavenya.c
        - ./lavenya
        - gcc -o mithungeorge mithungeorge.c
        - ./mithungeorge
