language: c
sudo: false # only for faster builds
compiler: 
 - clang
 - gcc
script:
 - gcc -o mithungeorge mithungeorge.c 
 - ./mithungeorge 
 - gcc -o lavenya lavenya.c 
 - ./lavenya 
  - gcc -o Antonette Antonette.c 
 - ./Antonette 
