language: c

sudo: false # only for faster builds

script:

  - clang -coverage -O0 Antonette.c -o Antonette

  - ./Antonette

  - gcov Antonette.c
  
    - clang -coverage -O0 mithungeorge.c -o mithungeorge

  - ./mithungeorge

  - gcov mithungeorge.c
  
    - clang -coverage -O0 lavenya.c -o lavenya

  - ./lavenya

  - gcov lavenya.c

 

after_success:

  - bash <(curl -s https://codecov.io/bash)
  
